# Use postgres/example user/password credentials
version: '3.9'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ttps
