spring.application.name=quecomemos
# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/ttps
#Test DATABASE
# spring.datasource.url=jdbc:postgresql://localhost:5433/ttps_test
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Swagger
springdoc.api-docs.path=/api-docs

#JWT config
jwt.secret.key=5SE/nTCibocu2SqRl8V8QG7+az0mqDFzeXhLhYWzS14=
# 24 horas en milisegundos - 24 * 60 * 60 * 1000 = 86400000
jwt.expiration.time=86400000
